backend:
  name: git-gateway
publish_mode: editorial_workflow
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "instance" # Used in routes, e.g., /admin/collections/blog
    label: "Instance" # Used in the UI
    folder: "_tangibleOccupy" # The path to the folder where the documents are stored
    filter:
      field: occurdate
      value: today
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "pubdate", widget: "datetime"}
      - {label: "Occurrence Date", name: "occurdate", widget: "datetime" }
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number", require: false}
      - {label: "Body", name: "body", widget: "markdown"}